### ISSUE TITLE
`$-2` in invention bodies

### ISSUE THREAD

**Issue by theoxo** [mlb2251/stitch#108]
To reproduce:
- On commit `f4a466dc8ca204c688edffb2637867783a47e355`, branch `main`
- `cargo run --bin=compress --release -- -a 3 --iterations 10 --fmt=dreamcoder --no-mismatch-check data/dc/logo_iteration_1.json`

**Comment by mlb2251** [comment]
Spent way too long on this one didnt think it would end up being so weirdly complicated. Still a bit more to figure out. Did fix a few issues in the current system along the way. Will finish it up some time soon. Working in #109

**Comment by mlb2251** [comment]
We should make a cargo test for this situation

**Comment by mlb2251** [comment]
Closed by #109
