### ISSUE TITLE
Add github integration tests

### ISSUE THREAD

**Issue by mlb2251** [mlb2251/stitch#14]
Ive never done this before but it'd be awesome to have it autocheck that train_200 and some other stuff compresses fine so we dont need to do that manually before merges

**Comment by theoxo** [comment]
I've done some stuff like this before using CircleCI. Honestly it was a massive pain to set up, but it's definitely nice to have. If I find myself with nothing else to do I can look into this

**Comment by theoxo** [comment]
Oh, I forget Github Actions is a thing now. This might not be that much of a pain then, although I'm not sure if we've really hit a "stable" point of compression yet?

**Comment by mlb2251** [comment]
Agreed, there are a lot of other priorities. I think at this point we're getting closer to this though

**Comment by mlb2251** [comment]
done
