### ISSUE TITLE
DC compat: remove inventions only used by a single Task

### ISSUE THREAD

**Issue by mlb2251** [mlb2251/stitch#51]
unclear where exactly to do this. It's not a huge priority bc it might just naturally happen automatically from the fact that inventions only used within single tasks arent that compressive hopefully. 

We could track a mapping from nodes to tasks, and then wherever we have `nodes` lists we just also have `tasks` lists built from that and we prune partial and total inventions based on those being non-singletons.

Perhaps without even allocating a separate `tasks` list we could just do this on the fly with lookups of tasks_of_node. Notably a single node can correspond to multiple tasks so you'd want to check a) if everyone is a singleton and if thats the case then you check if b) all those singletons are the same. Both those could be done with a quick .all() scan over .nodes.

**Comment by mlb2251** [comment]
Also add a new flag `--no_opt_single_task` which disables this pruning (much like no_opt_single_use)

**Comment by theoxo** [comment]
Fixed as of #84.
