### ISSUE TITLE
Follow a style guide and use a linter

### ISSUE THREAD

**Issue by theoxo** [mlb2251/stitch#78]
Right now the codebase has a pretty... disparate... style. Lots of very long lines, for example.

We may want to consider picking a Rust style guide to follow (are there any ones in widespread use?) and then setting up a linter (configuring rustc?) to make sure we have a somewhat uniform style.

This is _ultra_ low priority, however. Just something to keep in mind as the project matures.

**Comment by mlb2251** [comment]
Agreed! Linter wise I always hear about `clippy`
