### ISSUE TITLE
Write a javascript expression visualization tool

### ISSUE THREAD

**Issue by mlb2251** [mlb2251/stitch#81]
Like a little javascript website where you enter something in stitch or dreamcoder syntax and it renders it out as a tree. Also make it so you can include the expression in the URL so that stitch outputs can link directly to their javascript rendered versions.

This would really just help so much with debugging and visualizing :)

**Comment by mlb2251** [comment]
related: I do really want to visualize logo programs to tell how big these leading edges actually are bc what if they're all like single holes.

**Comment by theoxo** [comment]
Using `graphviz` could be another option! Usually pretty easy to turn tree datastructures into the required format in my experience (won't be as pretty, but probably less work :P).

**Comment by mlb2251** [comment]
lmao we did this in playskript eyyyy
