### ISSUE TITLE
Dreamcoder OCaml binary edits

### ISSUE THREAD

**Issue by mlb2251** [mlb2251/stitch#96]
This is a variety of edits we need to make in order to properly benchmark the OCaml code - e.g. inserting timing checks in the right places, logging intermediate results, etc.

We'll be using this fork of dreamcoder: https://github.com/mlb2251/stitch_dreamcoder

- [x] remove the verbose mode print statement that blows up the log files
- [x] add a json config field for which directory to use for `compressionMessages/`
- [x] have it also save the final invention / grammar / frontiers somewhere even when it **doesnt** accept it as an improvement so that we can analyze whether stitch does the same stuff even in those cases -> actually since we're analyzing topK that subsumes this
- [x] topK: make a version of the binary that just takes the json, adds a new "topK" toplevel field with the topK frontiers instead, and uses those in `restrict` during the worker thread stuff instead of using the other thing
-  [x] insert timing checks in the right places? Or call getrusage?
- [ ] decide how to handle memory checks.  split up binary into multiple parts so can do memory checks separately?

**Comment by mlb2251** [comment]
Disabled verbose mode but enabled writing compression messages during the un-timed part of the loop for a fair comparison. Added all timing checks.

**Comment by theoxo** [comment]
The topK binary change has been merged into `stitch_dreamcoder/icml_2021_supplement`.

**Comment by theoxo** [comment]
> add a json config field for which directory to use for compressionMessages/

Also merged into `stitch_dreamcoder/icml_2021_supplement`.

**Comment by theoxo** [comment]
> decide how to handle memory checks. split up binary into multiple parts so can do memory checks separately?

Can I help with this somehow? I'm busy after the group meeting today but could discuss it tomorrow if you wanna bounce some ideas off me

**Comment by mlb2251** [comment]
This is out of date but see the actual https://github.com/mlb2251/stitch_dreamcoder repo for the changes we made, closing this issue
